name: Generate and Deploy HTML

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      private_branch:
        description: 'Branch of the private repo to use'
        required: false
        default: 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout Private Repo
        uses: actions/checkout@v4
        with:
          repository: kwblackstone/ImageGalleryPrivate
          token: ${{ secrets.IMAGE }}
          path: ImageGalleryPrivate
          ref: ${{ github.event.inputs.private_branch || 'main' }}

      - name: Run HTML Generation Script
        run: |
          python3 ${{ github.workspace }}/ImageGalleryPrivate/src/generate.py ${{ github.workspace }}/data ${{ github.workspace }}/index.html

      - name: Deploy to GitHub Pages
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add index.html
          if [ -d "archives" ]; then
            git add archives/
          fi
          git commit -m "Auto-update index.html and archive pages"
          git push origin main
