name: Generate and Deploy HTML

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      private_branch:
        description: 'Branch of the private repo to use'
        required: false
        default: 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout Private Repo
        uses: actions/checkout@v4
        with:
          repository: kwblackstone/ImageGalleryPrivate
          token: ${{ secrets.IMAGE }}
          path: ImageGalleryPrivate
          ref: ${{ github.event.inputs.private_branch || 'main' }}

      - name: Run HTML Generation Script
        run: |
          python3 ${{ github.workspace }}/ImageGalleryPrivate/src/main.py ${{ github.workspace }}/data ${{ github.workspace }}/index.html

      - name: Check for Changes
        run: |
          if git diff --quiet; then
            echo "No changes detected."
            echo "changes=false" >> $GITHUB_ENV
          else
            echo "Changes detected."
            echo "changes=true" >> $GITHUB_ENV
          fi

      - name: Commit and Push Changes
        if: env.changes == 'true'
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add index.html
          if [ -d "archives" ]; then
            git add archives/
          fi
          if [ -d "images" ]; then
            git add images/
          fi
          git commit -m "Auto-update website"
          git push origin main

      - name: No Changes Detected
        if: env.changes == 'false'
        run: echo "No changes to deploy. Workflow completed without changes."
